### ISSUE TITLE
Check the status of subscription, If not purchased only then call launchPurchase()

### ISSUE THREAD

**Issue by shaivyanegi** [mightyfrog/Play-Billing-Library-Sample-for-Kotlin#1]
Hello Shigehiro Soejima,

Thanks for sharing this sample, I'm using it for SUBSCRIPTION, So I made a small change

`.setType(BillingClient.SkuType.SUBS)`

On tap of button, I'm directly calling launchPurchase()

```
btn_subcription.setOnClickListener {
           launchPurchase()
}
```

What I Want ? 
1. First of all, check the status of subscription, If already subscribed then just show a toast "Already purchased"
2. Otherwise call launchPurchase() function to purchase Subscription

Thanks

**Comment by mightyfrog** [comment]
Use getPurchases(type) to get a list of purchased items and then match skus. Is that what you want?????

**Comment by shaivyanegi** [comment]
Thanks for writing this, but be frank with you, I'm not getting what exactly ? Could you please put that condition on button tap
